version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - './app/server:/app/server'
      - './app/client:/app/client'
